### PR TITLE
enable minestom

### PR DESCRIPTION
**Pull request by Nopock**
I switched to minestom-ce which is a more stable repo.

https://github.com/hollow-cube/minestom-ce

### CODE REVIEW

**Comment by lucko** [comment]
That repo is archived now, so much for being stable... :]

Looking at the Minestom readme, it seems like they are still using Jitpack :(

**Comment by Nopock** [comment]
Just saw that, unfortunate that they use jipack 😭

**Comment by MelonHell** [comment]
@lucko Minestom no longer uses jitpack

**Comment by nateweisz** [comment]
> @lucko now Minestom does not use jitpack, only mavenCentral
> 
> 
> 
> https://github.com/Minestom/Minestom/commit/5182f19dd7275073e54be5449f938fdedf2afcec

They also no longer support extensions, unless you'd like to provide spark as a lib

**Comment by MelonHell** [comment]
> They also no longer support extensions, unless you'd like to provide spark as a lib

To support extensions there is https://github.com/hollow-cube/minestom-ce-extensions. In general, I agree, extensions are not a desirable option, a library is better

**Pull request closed without merging**
