### PR TITLE
Use Bukkit#getName() for server name

### PR DESCRIPTION
**Pull request by powercasgamer**
Paper (1.20.6+) Before: firefox_W3qNuFf7p9

Paper After: firefox_g9RutfYRN8

Spigot: firefox_UZIQFJuCmO

Maybe need to check if the version contains Spigot then use 'Spigot' as the server name? But imho Spigot..

### CODE REVIEW

**Comment by EterNityCH** [comment]
This would fix the existing issue on 1.21. LGTM

**Review by EterNityCH — APPROVED** [review]

**Comment by lucko** [comment]
Unfortunately the server type string is used to determine which mappings to use -- https://github.com/lucko/spark-mappings/blob/master/dist/mappings.json#L3

Instead could we incorporate the server brand into the version string?

**Comment by powercasgamer** [comment]
> Unfortunately the server type string is used to determine which mappings to use -- [lucko/spark-mappings@`master`/dist/mappings.json#L3](https://github.com/lucko/spark-mappings/blob/master/dist/mappings.json?rgh-link-date=2024-07-04T19%3A31%3A02Z#L3)
> 
> Instead could we incorporate the server brand into the version string?

Something like this? 
Paper:  firefox_5UoVDQtlul

Spigot:  firefox_glQYKaQ1Ha

For Spigot we could also check if the string contains "Spigot" and then just not add it or something.

**Comment by lucko** [comment]
Decided to just add a `brand` field separate from `name` so we can show it nicely :)

https://github.com/lucko/spark-viewer/commit/568817f36076bbf596e2c782ba667aece4bdb299

Thank you for the PR!

**Pull request closed without merging**
