### PR TITLE
Expose a Profiler API in `spark-api`

### PR DESCRIPTION
**Pull request by bram-pkg**
Hi, @lucko 

As I wrote in #130, here is a draft PR for the Profiler API. This is just a *small* start.
This API addition will allow to programmatically start and stop the profiler.

When the profiler is stopped, a `ProfilerReport` object will be returned containing the URL to the viewer (more fields possible).

I am looking forward to hearing your thoughts about this.

### CODE REVIEW

**Comment by lucko** [comment]
At first glance this looks great - I'll try to take a closer look over the weekend.

**Comment by bramceulemans** [comment]
Awesome, great that you're open to the idea!

**Comment by PaintNinja** [comment]
Any update on this? It would be very handy to have an API for Spark's profiling functionality

**Comment by bram-pkg** [comment]
Sorry, yes! Completely forgot about this.

**Comment by Matyrobbrt** [comment]
I've gone ahead and superseded this PR in #229

**Pull request closed without merging**
